site_name: PolarRoute
repo_url: https://github.com/bas-amop/PolarRoute
edit_uri: edit/main/docs/
theme: 
  name: material
  logo: https://cdn.web.bas.ac.uk/bas-style-kit/0.7.3/img/logos-symbols/bas-roundel-inverse-transparent-64.png
  favicon: https://cdn.web.bas.ac.uk/bas-style-kit/0.7.3/img/favicon/favicon-16x16.png
  icon:
    repo: fontawesome/brands/github
  features:
    # Enables copying of code blocks
    - content.code.copy
    # Enables "edit this page" to contribute to docs
    - content.action.edit
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins: 
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [., polar_route]
          options:
            docstring_style: google
            # show_object_full_path: true
            merge_init_into_class: true
            show_docstring_functions: true
            show_docstring_classes: true
            show_source: false
  - mkdocs-autoapi:
      autoapi_dir: polar_route
      autoapi_ignore:
        - "tests/*"
      autoapi_add_nav_entry: true
      autoapi_file_patterns:
        - "*.py"
  - include-markdown:
      rewrite_relative_urls: true

nav:
  - Home: index.md
  - installation.md
  - overview.md
  - examples.md
  - cli.md
  - Configuration:
    - Overview: config/overview.md
    - Vessel Performance: config/vessel_performance.md
    - Vessel Gallery: config/vessel_gallery.md
    - Route Planning: config/route_planning.md
  - output.md
  - Methods:
    - Vessel Performance: methods/vessel_performance.md
    - Resistance Models: methods/resistance_models.md
    - Route Calculation: methods/route_calculation.md
    - Route Optimisation: methods/route_optimisation.md
  - Reference:
    - Model Parameters: reference/model_parameters.md

markdown_extensions:
  - toc:
      permalink: True
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji # (1)!
      emoji_generator: !!python/name:material.extensions.emoji.to_svg


copyright: Copyright &copy; 2026 British Antarctic Survey